-- Portable SQL: runs on PostgreSQL and on H2 in PostgreSQL mode.

create table app_user (
    id              bigint generated by default as identity primary key,
    username        varchar(50)  not null unique,
    password_hash   varchar(100) not null,
    full_name       varchar(100) not null,
    role            varchar(20)  not null,
    enabled         boolean      not null default true,
    failed_attempts int          not null default 0,
    locked_until    timestamp with time zone,
    created_at      timestamp with time zone not null
);

create table refresh_token (
    id         bigint generated by default as identity primary key,
    token_hash varchar(64) not null unique,
    user_id    bigint      not null references app_user (id),
    expires_at timestamp with time zone not null,
    revoked    boolean     not null default false
);

create table photo (
    id           uuid primary key,
    path         varchar(500) not null,
    content_type varchar(50)  not null,
    size_bytes   bigint       not null,
    uploaded_by  bigint references app_user (id),
    uploaded_at  timestamp with time zone not null
);

create sequence driver_code_seq start with 1;
create sequence rickshaw_number_seq start with 1;

create table driver (
    id                  bigint generated by default as identity primary key,
    driver_code         varchar(20)  not null unique,
    full_name           varchar(100) not null,
    father_name         varchar(100) not null,
    date_of_birth       date         not null,
    gender              varchar(10)  not null,
    nid                 varchar(17)  not null unique,
    licence_no          varchar(30),
    mobile              varchar(11)  not null,
    present_division    varchar(50)  not null,
    present_district    varchar(50)  not null,
    present_thana       varchar(50)  not null,
    present_line        varchar(200) not null,
    permanent_division  varchar(50)  not null,
    permanent_district  varchar(50)  not null,
    permanent_thana     varchar(50)  not null,
    permanent_line      varchar(200) not null,
    blood_group         varchar(5),
    emergency_name      varchar(100),
    emergency_phone     varchar(11),
    photo_id            uuid         not null references photo (id),
    nid_front_id        uuid references photo (id),
    nid_back_id         uuid references photo (id),
    status              varchar(20)  not null,
    registered_by       bigint       not null references app_user (id),
    registered_at       timestamp with time zone not null,
    updated_at          timestamp with time zone not null
);
create index idx_driver_mobile on driver (mobile);

create table owner (
    id         bigint generated by default as identity primary key,
    full_name  varchar(100) not null,
    nid        varchar(17)  not null unique,
    mobile     varchar(11)  not null,
    division   varchar(50)  not null,
    district   varchar(50)  not null,
    thana      varchar(50)  not null,
    line       varchar(200) not null,
    created_by bigint       not null references app_user (id),
    created_at timestamp with time zone not null
);

create table rickshaw (
    id              bigint generated by default as identity primary key,
    rickshaw_number varchar(20)  not null unique,
    chassis_no      varchar(50),
    motor_no        varchar(50),
    color           varchar(30),
    model           varchar(50),
    thana           varchar(50)  not null,
    photo_id        uuid         not null references photo (id),
    rear_photo_id   uuid references photo (id),
    owner_id        bigint       not null references owner (id),
    status          varchar(20)  not null,
    registered_by   bigint       not null references app_user (id),
    registered_at   timestamp with time zone not null,
    updated_at      timestamp with time zone not null
);
create index idx_rickshaw_thana on rickshaw (thana);
create index idx_rickshaw_registered_at on rickshaw (registered_at);

-- "One active assignment per rickshaw and per driver" is enforced in AssignmentService
-- (partial unique indexes are not portable to H2).
create table assignment (
    id          bigint generated by default as identity primary key,
    rickshaw_id bigint not null references rickshaw (id),
    driver_id   bigint not null references driver (id),
    from_date   timestamp with time zone not null,
    to_date     timestamp with time zone,
    assigned_by bigint not null references app_user (id)
);
create index idx_assignment_rickshaw on assignment (rickshaw_id, to_date);
create index idx_assignment_driver on assignment (driver_id, to_date);

create table audit_log (
    id        bigint generated by default as identity primary key,
    actor_id  bigint references app_user (id),
    action    varchar(30)  not null,
    entity    varchar(30)  not null,
    entity_id varchar(50),
    details   varchar(1000),
    at        timestamp with time zone not null
);
create index idx_audit_at on audit_log (at);
